# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" > mynetmauiapp.keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch mynetmauiapp.keystore.asc > mynetmauiapp.keystore
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install .NET MAUI 
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build MyNetMauiApp/MyNetMauiApp.csproj -c Release -f net7.0-android /p:AndroidSigningKeyStore=mynetmauiapp.keystore /p:AndroidSigningKeyAlias=mynetmauikey /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: |
          ./**/*.aab
          ./**/*.apk
